### ISSUE TITLE
auth service to proxy auth client

### ISSUE THREAD

**Issue by nurali-techie** [fabric8-services/fabric8-common#63]
Add auth_service which provides methods to call different auth_service_api ([f8-auth](https://github.com/fabric8-services/fabric8-auth/)) using auth_client ([f8-auth-client](https://github.com/fabric8-services/fabric8-auth-client)).

- [x] CheckResourceScope: calls [ScopesResource](https://github.com/fabric8-services/fabric8-auth-client/blob/master/auth/resource.go#L115)

**Comment by alexeykazakov** [comment]
I don't think we should proxy everything. Clients can use auth client directly. Some most used methods can be added to the existing service - https://github.com/fabric8-services/fabric8-common/blob/master/auth/service.go but we need to be specific. Closing.
