### ISSUE TITLE
Recover panics in /httpsupport/proxy.go

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-common#75]
In go 1.11 a new panic was introduced in `reverseproxy.go`, see the following links for details:

golang/go#23643
golang/go#28239

The suggested fix when encountering this panic is to recover it in the `proxy.go/route()` function, with a deferred function, along these lines:

```
defer func() {
        if r := recover(); r != nil {
            log.Warn(ctx, map[string]interface{}{
                "Recovered": r,
            }, "Recovered from RouteHTTP panic")
        }
    }()
```

**Comment by alexeykazakov** [comment]
Related to https://github.com/fabric8-services/fabric8-auth/issues/734

**Comment by alexeykazakov** [comment]
Fixed in https://github.com/fabric8-services/fabric8-common/pull/80
